// Generated by gencpp from file planning_msgs/Polygon2D.msg
// DO NOT EDIT!


#ifndef PLANNING_MSGS_MESSAGE_POLYGON2D_H
#define PLANNING_MSGS_MESSAGE_POLYGON2D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <planning_msgs/Point2D.h>

namespace planning_msgs
{
template <class ContainerAllocator>
struct Polygon2D_
{
  typedef Polygon2D_<ContainerAllocator> Type;

  Polygon2D_()
    : points()  {
    }
  Polygon2D_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::planning_msgs::Point2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::planning_msgs::Point2D_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::planning_msgs::Polygon2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planning_msgs::Polygon2D_<ContainerAllocator> const> ConstPtr;

}; // struct Polygon2D_

typedef ::planning_msgs::Polygon2D_<std::allocator<void> > Polygon2D;

typedef boost::shared_ptr< ::planning_msgs::Polygon2D > Polygon2DPtr;
typedef boost::shared_ptr< ::planning_msgs::Polygon2D const> Polygon2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planning_msgs::Polygon2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planning_msgs::Polygon2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planning_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'planning_msgs': ['/home/lukewen/gym_gazebo/gym_gazebo/envs/installation/catkin_ws/src/mav_comm/planning_msgs/msg'], 'mav_msgs': ['/home/lukewen/gym_gazebo/gym_gazebo/envs/installation/catkin_ws/src/mav_comm/mav_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planning_msgs::Polygon2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planning_msgs::Polygon2D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planning_msgs::Polygon2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planning_msgs::Polygon2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning_msgs::Polygon2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning_msgs::Polygon2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planning_msgs::Polygon2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f02263beef99aa03117a577a3eb879d";
  }

  static const char* value(const ::planning_msgs::Polygon2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f02263beef99aa0ULL;
  static const uint64_t static_value2 = 0x3117a577a3eb879dULL;
};

template<class ContainerAllocator>
struct DataType< ::planning_msgs::Polygon2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planning_msgs/Polygon2D";
  }

  static const char* value(const ::planning_msgs::Polygon2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planning_msgs::Polygon2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A specification of a 2D polygon where the first and last points are assumed to be connected.\n\
planning_msgs/Point2D[] points\n\
\n\
================================================================================\n\
MSG: planning_msgs/Point2D\n\
# This contains the position of a 2D point.\n\
float64 x\n\
float64 y\n\
";
  }

  static const char* value(const ::planning_msgs::Polygon2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planning_msgs::Polygon2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Polygon2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planning_msgs::Polygon2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planning_msgs::Polygon2D_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::planning_msgs::Point2D_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNING_MSGS_MESSAGE_POLYGON2D_H
