# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from exploration3d_msgs/FreeSpaceFrontierRepresentative.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class FreeSpaceFrontierRepresentative(genpy.Message):
  _md5sum = "f2040b5472a070e8f5b7ea2b2735cd22"
  _type = "exploration3d_msgs/FreeSpaceFrontierRepresentative"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# A freespace frontier representative is the centroid of a group of connected freespace frontier voxels of some size 

# the centroid of the freespace frontier voxel cluster
geometry_msgs/Point p
# the normal to the freespace frontier voxel surface at centroid
geometry_msgs/Vector3 n
# number of voxels in the freespace frontier cluster
uint32 nvx

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['p','n','nvx']
  _slot_types = ['geometry_msgs/Point','geometry_msgs/Vector3','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       p,n,nvx

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FreeSpaceFrontierRepresentative, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.p is None:
        self.p = geometry_msgs.msg.Point()
      if self.n is None:
        self.n = geometry_msgs.msg.Vector3()
      if self.nvx is None:
        self.nvx = 0
    else:
      self.p = geometry_msgs.msg.Point()
      self.n = geometry_msgs.msg.Vector3()
      self.nvx = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6dI().pack(_x.p.x, _x.p.y, _x.p.z, _x.n.x, _x.n.y, _x.n.z, _x.nvx))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.p is None:
        self.p = geometry_msgs.msg.Point()
      if self.n is None:
        self.n = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 52
      (_x.p.x, _x.p.y, _x.p.z, _x.n.x, _x.n.y, _x.n.z, _x.nvx,) = _get_struct_6dI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6dI().pack(_x.p.x, _x.p.y, _x.p.z, _x.n.x, _x.n.y, _x.n.z, _x.nvx))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.p is None:
        self.p = geometry_msgs.msg.Point()
      if self.n is None:
        self.n = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 52
      (_x.p.x, _x.p.y, _x.p.z, _x.n.x, _x.n.y, _x.n.z, _x.nvx,) = _get_struct_6dI().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6dI = None
def _get_struct_6dI():
    global _struct_6dI
    if _struct_6dI is None:
        _struct_6dI = struct.Struct("<6dI")
    return _struct_6dI
