(cl:defpackage exploration3d_msgs-msg
  (:use )
  (:export
   "<EXPLORATIONTASK>"
   "EXPLORATIONTASK"
   "<EXPLORATIONTASKUPDATE>"
   "EXPLORATIONTASKUPDATE"
   "<FREESPACEFRONTIERREPRESENTATIVE>"
   "FREESPACEFRONTIERREPRESENTATIVE"
   "<FREESPACEFRONTIERREPRESENTATIVES>"
   "FREESPACEFRONTIERREPRESENTATIVES"
   "<SURFACEFRONTIERREPRESENTATIVE>"
   "SURFACEFRONTIERREPRESENTATIVE"
   "<SURFACEFRONTIERREPRESENTATIVES>"
   "SURFACEFRONTIERREPRESENTATIVES"
   "<SURFACEFRONTIERUPDATES>"
   "SURFACEFRONTIERUPDATES"
  ))

