(cl:defpackage navigation_3d_msgs-msg
  (:use )
  (:export
   "<NAVIGATIONSTATUS>"
   "NAVIGATIONSTATUS"
   "<PATHNAVIGATIONACTION>"
   "PATHNAVIGATIONACTION"
   "<PATHNAVIGATIONACTIONFEEDBACK>"
   "PATHNAVIGATIONACTIONFEEDBACK"
   "<PATHNAVIGATIONACTIONGOAL>"
   "PATHNAVIGATIONACTIONGOAL"
   "<PATHNAVIGATIONACTIONRESULT>"
   "PATHNAVIGATIONACTIONRESULT"
   "<PATHNAVIGATIONFEEDBACK>"
   "PATHNAVIGATIONFEEDBACK"
   "<PATHNAVIGATIONGOAL>"
   "PATHNAVIGATIONGOAL"
   "<PATHNAVIGATIONRESULT>"
   "PATHNAVIGATIONRESULT"
   "<ROBOTINFO>"
   "ROBOTINFO"
   "<SURFACEMAP>"
   "SURFACEMAP"
  ))

