; Auto-generated. Do not edit!


(cl:in-package navigation_3d_msgs-msg)


;//! \htmlinclude PathNavigationFeedback.msg.html

(cl:defclass <PathNavigationFeedback> (roslisp-msg-protocol:ros-message)
  ((base_position
    :reader base_position
    :initarg :base_position
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped))
   (next_wp
    :reader next_wp
    :initarg :next_wp
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass PathNavigationFeedback (<PathNavigationFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PathNavigationFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PathNavigationFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name navigation_3d_msgs-msg:<PathNavigationFeedback> is deprecated: use navigation_3d_msgs-msg:PathNavigationFeedback instead.")))

(cl:ensure-generic-function 'base_position-val :lambda-list '(m))
(cl:defmethod base_position-val ((m <PathNavigationFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader navigation_3d_msgs-msg:base_position-val is deprecated.  Use navigation_3d_msgs-msg:base_position instead.")
  (base_position m))

(cl:ensure-generic-function 'next_wp-val :lambda-list '(m))
(cl:defmethod next_wp-val ((m <PathNavigationFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader navigation_3d_msgs-msg:next_wp-val is deprecated.  Use navigation_3d_msgs-msg:next_wp instead.")
  (next_wp m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PathNavigationFeedback>) ostream)
  "Serializes a message object of type '<PathNavigationFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'base_position) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'next_wp) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PathNavigationFeedback>) istream)
  "Deserializes a message object of type '<PathNavigationFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'base_position) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'next_wp) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PathNavigationFeedback>)))
  "Returns string type for a message object of type '<PathNavigationFeedback>"
  "navigation_3d_msgs/PathNavigationFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PathNavigationFeedback)))
  "Returns string type for a message object of type 'PathNavigationFeedback"
  "navigation_3d_msgs/PathNavigationFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PathNavigationFeedback>)))
  "Returns md5sum for a message object of type '<PathNavigationFeedback>"
  "70ad3497649caabc377bf9d2f09ab0e2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PathNavigationFeedback)))
  "Returns md5sum for a message object of type 'PathNavigationFeedback"
  "70ad3497649caabc377bf9d2f09ab0e2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PathNavigationFeedback>)))
  "Returns full string definition for message of type '<PathNavigationFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped base_position~%geometry_msgs/PoseStamped next_wp~%~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PathNavigationFeedback)))
  "Returns full string definition for message of type 'PathNavigationFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped base_position~%geometry_msgs/PoseStamped next_wp~%~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PathNavigationFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'base_position))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'next_wp))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PathNavigationFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PathNavigationFeedback
    (cl:cons ':base_position (base_position msg))
    (cl:cons ':next_wp (next_wp msg))
))
