; Auto-generated. Do not edit!


(cl:in-package navigation_3d_msgs-msg)


;//! \htmlinclude PathNavigationResult.msg.html

(cl:defclass <PathNavigationResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PathNavigationResult (<PathNavigationResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PathNavigationResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PathNavigationResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name navigation_3d_msgs-msg:<PathNavigationResult> is deprecated: use navigation_3d_msgs-msg:PathNavigationResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PathNavigationResult>) ostream)
  "Serializes a message object of type '<PathNavigationResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PathNavigationResult>) istream)
  "Deserializes a message object of type '<PathNavigationResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PathNavigationResult>)))
  "Returns string type for a message object of type '<PathNavigationResult>"
  "navigation_3d_msgs/PathNavigationResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PathNavigationResult)))
  "Returns string type for a message object of type 'PathNavigationResult"
  "navigation_3d_msgs/PathNavigationResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PathNavigationResult>)))
  "Returns md5sum for a message object of type '<PathNavigationResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PathNavigationResult)))
  "Returns md5sum for a message object of type 'PathNavigationResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PathNavigationResult>)))
  "Returns full string definition for message of type '<PathNavigationResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PathNavigationResult)))
  "Returns full string definition for message of type 'PathNavigationResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PathNavigationResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PathNavigationResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PathNavigationResult
))
