// Generated by gencpp from file exploration3d_msgs/FreeSpaceFrontierRepresentatives.msg
// DO NOT EDIT!


#ifndef EXPLORATION3D_MSGS_MESSAGE_FREESPACEFRONTIERREPRESENTATIVES_H
#define EXPLORATION3D_MSGS_MESSAGE_FREESPACEFRONTIERREPRESENTATIVES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <exploration3d_msgs/FreeSpaceFrontierRepresentative.h>

namespace exploration3d_msgs
{
template <class ContainerAllocator>
struct FreeSpaceFrontierRepresentatives_
{
  typedef FreeSpaceFrontierRepresentatives_<ContainerAllocator> Type;

  FreeSpaceFrontierRepresentatives_()
    : header()
    , frontiers()  {
    }
  FreeSpaceFrontierRepresentatives_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , frontiers(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::exploration3d_msgs::FreeSpaceFrontierRepresentative_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::exploration3d_msgs::FreeSpaceFrontierRepresentative_<ContainerAllocator> >::other >  _frontiers_type;
  _frontiers_type frontiers;





  typedef boost::shared_ptr< ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator> const> ConstPtr;

}; // struct FreeSpaceFrontierRepresentatives_

typedef ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<std::allocator<void> > FreeSpaceFrontierRepresentatives;

typedef boost::shared_ptr< ::exploration3d_msgs::FreeSpaceFrontierRepresentatives > FreeSpaceFrontierRepresentativesPtr;
typedef boost::shared_ptr< ::exploration3d_msgs::FreeSpaceFrontierRepresentatives const> FreeSpaceFrontierRepresentativesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exploration3d_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'exploration3d_msgs': ['/home/lukewen/gym_gazebo/gym_gazebo/envs/installation/catkin_ws/src/nav_common/exploration3d_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc74daa8665957dca20e7eac4bdcbf22";
  }

  static const char* value(const ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc74daa8665957dcULL;
  static const uint64_t static_value2 = 0xa20e7eac4bdcbf22ULL;
};

template<class ContainerAllocator>
struct DataType< ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exploration3d_msgs/FreeSpaceFrontierRepresentatives";
  }

  static const char* value(const ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
exploration3d_msgs/FreeSpaceFrontierRepresentative[] frontiers\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: exploration3d_msgs/FreeSpaceFrontierRepresentative\n\
# A freespace frontier representative is the centroid of a group of connected freespace frontier voxels of some size \n\
\n\
# the centroid of the freespace frontier voxel cluster\n\
geometry_msgs/Point p\n\
# the normal to the freespace frontier voxel surface at centroid\n\
geometry_msgs/Vector3 n\n\
# number of voxels in the freespace frontier cluster\n\
uint32 nvx\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.frontiers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FreeSpaceFrontierRepresentatives_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exploration3d_msgs::FreeSpaceFrontierRepresentatives_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "frontiers[]" << std::endl;
    for (size_t i = 0; i < v.frontiers.size(); ++i)
    {
      s << indent << "  frontiers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::exploration3d_msgs::FreeSpaceFrontierRepresentative_<ContainerAllocator> >::stream(s, indent + "    ", v.frontiers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORATION3D_MSGS_MESSAGE_FREESPACEFRONTIERREPRESENTATIVES_H
