// Generated by gencpp from file exploration3d_msgs/GetFreeSpaceFrontierRepresentatives.msg
// DO NOT EDIT!


#ifndef EXPLORATION3D_MSGS_MESSAGE_GETFREESPACEFRONTIERREPRESENTATIVES_H
#define EXPLORATION3D_MSGS_MESSAGE_GETFREESPACEFRONTIERREPRESENTATIVES_H

#include <ros/service_traits.h>


#include <exploration3d_msgs/GetFreeSpaceFrontierRepresentativesRequest.h>
#include <exploration3d_msgs/GetFreeSpaceFrontierRepresentativesResponse.h>


namespace exploration3d_msgs
{

struct GetFreeSpaceFrontierRepresentatives
{

typedef GetFreeSpaceFrontierRepresentativesRequest Request;
typedef GetFreeSpaceFrontierRepresentativesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFreeSpaceFrontierRepresentatives
} // namespace exploration3d_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentatives > {
  static const char* value()
  {
    return "42bad0289ab9e4d55cd64632c44f3f09";
  }

  static const char* value(const ::exploration3d_msgs::GetFreeSpaceFrontierRepresentatives&) { return value(); }
};

template<>
struct DataType< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentatives > {
  static const char* value()
  {
    return "exploration3d_msgs/GetFreeSpaceFrontierRepresentatives";
  }

  static const char* value(const ::exploration3d_msgs::GetFreeSpaceFrontierRepresentatives&) { return value(); }
};


// service_traits::MD5Sum< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentativesRequest> should match 
// service_traits::MD5Sum< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentatives > 
template<>
struct MD5Sum< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentativesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentatives >::value();
  }
  static const char* value(const ::exploration3d_msgs::GetFreeSpaceFrontierRepresentativesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentativesRequest> should match 
// service_traits::DataType< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentatives > 
template<>
struct DataType< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentativesRequest>
{
  static const char* value()
  {
    return DataType< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentatives >::value();
  }
  static const char* value(const ::exploration3d_msgs::GetFreeSpaceFrontierRepresentativesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentativesResponse> should match 
// service_traits::MD5Sum< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentatives > 
template<>
struct MD5Sum< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentativesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentatives >::value();
  }
  static const char* value(const ::exploration3d_msgs::GetFreeSpaceFrontierRepresentativesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentativesResponse> should match 
// service_traits::DataType< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentatives > 
template<>
struct DataType< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentativesResponse>
{
  static const char* value()
  {
    return DataType< ::exploration3d_msgs::GetFreeSpaceFrontierRepresentatives >::value();
  }
  static const char* value(const ::exploration3d_msgs::GetFreeSpaceFrontierRepresentativesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXPLORATION3D_MSGS_MESSAGE_GETFREESPACEFRONTIERREPRESENTATIVES_H
