// Generated by gencpp from file exploration3d_msgs/GetSurfaceFrontierUpdatesRequest.msg
// DO NOT EDIT!


#ifndef EXPLORATION3D_MSGS_MESSAGE_GETSURFACEFRONTIERUPDATESREQUEST_H
#define EXPLORATION3D_MSGS_MESSAGE_GETSURFACEFRONTIERUPDATESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace exploration3d_msgs
{
template <class ContainerAllocator>
struct GetSurfaceFrontierUpdatesRequest_
{
  typedef GetSurfaceFrontierUpdatesRequest_<ContainerAllocator> Type;

  GetSurfaceFrontierUpdatesRequest_()
    : base_pose()  {
    }
  GetSurfaceFrontierUpdatesRequest_(const ContainerAllocator& _alloc)
    : base_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _base_pose_type;
  _base_pose_type base_pose;





  typedef boost::shared_ptr< ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetSurfaceFrontierUpdatesRequest_

typedef ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<std::allocator<void> > GetSurfaceFrontierUpdatesRequest;

typedef boost::shared_ptr< ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest > GetSurfaceFrontierUpdatesRequestPtr;
typedef boost::shared_ptr< ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest const> GetSurfaceFrontierUpdatesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exploration3d_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'exploration3d_msgs': ['/home/lukewen/gym_gazebo/gym_gazebo/envs/installation/catkin_ws/src/nav_common/exploration3d_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "735bd3b58bedaeab43b3509fcd91d5f9";
  }

  static const char* value(const ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x735bd3b58bedaeabULL;
  static const uint64_t static_value2 = 0x43b3509fcd91d5f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exploration3d_msgs/GetSurfaceFrontierUpdatesRequest";
  }

  static const char* value(const ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped base_pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.base_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSurfaceFrontierUpdatesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exploration3d_msgs::GetSurfaceFrontierUpdatesRequest_<ContainerAllocator>& v)
  {
    s << indent << "base_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.base_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORATION3D_MSGS_MESSAGE_GETSURFACEFRONTIERUPDATESREQUEST_H
