// Generated by gencpp from file exploration3d_msgs/GetSurfaceFrontierRepresentatives.msg
// DO NOT EDIT!


#ifndef EXPLORATION3D_MSGS_MESSAGE_GETSURFACEFRONTIERREPRESENTATIVES_H
#define EXPLORATION3D_MSGS_MESSAGE_GETSURFACEFRONTIERREPRESENTATIVES_H

#include <ros/service_traits.h>


#include <exploration3d_msgs/GetSurfaceFrontierRepresentativesRequest.h>
#include <exploration3d_msgs/GetSurfaceFrontierRepresentativesResponse.h>


namespace exploration3d_msgs
{

struct GetSurfaceFrontierRepresentatives
{

typedef GetSurfaceFrontierRepresentativesRequest Request;
typedef GetSurfaceFrontierRepresentativesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSurfaceFrontierRepresentatives
} // namespace exploration3d_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exploration3d_msgs::GetSurfaceFrontierRepresentatives > {
  static const char* value()
  {
    return "ceb941e9622ea77681232187bc67de45";
  }

  static const char* value(const ::exploration3d_msgs::GetSurfaceFrontierRepresentatives&) { return value(); }
};

template<>
struct DataType< ::exploration3d_msgs::GetSurfaceFrontierRepresentatives > {
  static const char* value()
  {
    return "exploration3d_msgs/GetSurfaceFrontierRepresentatives";
  }

  static const char* value(const ::exploration3d_msgs::GetSurfaceFrontierRepresentatives&) { return value(); }
};


// service_traits::MD5Sum< ::exploration3d_msgs::GetSurfaceFrontierRepresentativesRequest> should match 
// service_traits::MD5Sum< ::exploration3d_msgs::GetSurfaceFrontierRepresentatives > 
template<>
struct MD5Sum< ::exploration3d_msgs::GetSurfaceFrontierRepresentativesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exploration3d_msgs::GetSurfaceFrontierRepresentatives >::value();
  }
  static const char* value(const ::exploration3d_msgs::GetSurfaceFrontierRepresentativesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exploration3d_msgs::GetSurfaceFrontierRepresentativesRequest> should match 
// service_traits::DataType< ::exploration3d_msgs::GetSurfaceFrontierRepresentatives > 
template<>
struct DataType< ::exploration3d_msgs::GetSurfaceFrontierRepresentativesRequest>
{
  static const char* value()
  {
    return DataType< ::exploration3d_msgs::GetSurfaceFrontierRepresentatives >::value();
  }
  static const char* value(const ::exploration3d_msgs::GetSurfaceFrontierRepresentativesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exploration3d_msgs::GetSurfaceFrontierRepresentativesResponse> should match 
// service_traits::MD5Sum< ::exploration3d_msgs::GetSurfaceFrontierRepresentatives > 
template<>
struct MD5Sum< ::exploration3d_msgs::GetSurfaceFrontierRepresentativesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exploration3d_msgs::GetSurfaceFrontierRepresentatives >::value();
  }
  static const char* value(const ::exploration3d_msgs::GetSurfaceFrontierRepresentativesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exploration3d_msgs::GetSurfaceFrontierRepresentativesResponse> should match 
// service_traits::DataType< ::exploration3d_msgs::GetSurfaceFrontierRepresentatives > 
template<>
struct DataType< ::exploration3d_msgs::GetSurfaceFrontierRepresentativesResponse>
{
  static const char* value()
  {
    return DataType< ::exploration3d_msgs::GetSurfaceFrontierRepresentatives >::value();
  }
  static const char* value(const ::exploration3d_msgs::GetSurfaceFrontierRepresentativesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXPLORATION3D_MSGS_MESSAGE_GETSURFACEFRONTIERREPRESENTATIVES_H
