// Generated by gencpp from file exploration3d_msgs/SurfaceFrontierRepresentative.msg
// DO NOT EDIT!


#ifndef EXPLORATION3D_MSGS_MESSAGE_SURFACEFRONTIERREPRESENTATIVE_H
#define EXPLORATION3D_MSGS_MESSAGE_SURFACEFRONTIERREPRESENTATIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace exploration3d_msgs
{
template <class ContainerAllocator>
struct SurfaceFrontierRepresentative_
{
  typedef SurfaceFrontierRepresentative_<ContainerAllocator> Type;

  SurfaceFrontierRepresentative_()
    : p()
    , length(0.0)
    , parent_length(0.0)
    , corner_1()
    , corner_2()
    , parent_corner_1()
    , parent_corner_2()
    , v()
    , f_grad()
    , n()
    , a(0.0)
    , is_floor(false)  {
    }
  SurfaceFrontierRepresentative_(const ContainerAllocator& _alloc)
    : p(_alloc)
    , length(0.0)
    , parent_length(0.0)
    , corner_1(_alloc)
    , corner_2(_alloc)
    , parent_corner_1(_alloc)
    , parent_corner_2(_alloc)
    , v(_alloc)
    , f_grad(_alloc)
    , n(_alloc)
    , a(0.0)
    , is_floor(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _p_type;
  _p_type p;

   typedef float _length_type;
  _length_type length;

   typedef float _parent_length_type;
  _parent_length_type parent_length;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _corner_1_type;
  _corner_1_type corner_1;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _corner_2_type;
  _corner_2_type corner_2;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _parent_corner_1_type;
  _parent_corner_1_type parent_corner_1;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _parent_corner_2_type;
  _parent_corner_2_type parent_corner_2;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _v_type;
  _v_type v;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _f_grad_type;
  _f_grad_type f_grad;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _n_type;
  _n_type n;

   typedef double _a_type;
  _a_type a;

   typedef uint8_t _is_floor_type;
  _is_floor_type is_floor;





  typedef boost::shared_ptr< ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator> const> ConstPtr;

}; // struct SurfaceFrontierRepresentative_

typedef ::exploration3d_msgs::SurfaceFrontierRepresentative_<std::allocator<void> > SurfaceFrontierRepresentative;

typedef boost::shared_ptr< ::exploration3d_msgs::SurfaceFrontierRepresentative > SurfaceFrontierRepresentativePtr;
typedef boost::shared_ptr< ::exploration3d_msgs::SurfaceFrontierRepresentative const> SurfaceFrontierRepresentativeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exploration3d_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'exploration3d_msgs': ['/home/lukewen/gym_gazebo/gym_gazebo/envs/installation/catkin_ws/src/nav_common/exploration3d_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed77d51612da3010c5ebfa0790477505";
  }

  static const char* value(const ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed77d51612da3010ULL;
  static const uint64_t static_value2 = 0xc5ebfa0790477505ULL;
};

template<class ContainerAllocator>
struct DataType< ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exploration3d_msgs/SurfaceFrontierRepresentative";
  }

  static const char* value(const ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A surface frontier is a portion of a large surface frontier contour. If the contour length is less than a certain threshold, the entire contour is represented using a single point p, its length and the two corner points as a frontier.\n\
\n\
# If the contour's length exceeds this threshold, the contour is segmented to portions with some length, where each segment's mid-point and its length is reported as a frontier. Most such segments don't carry corner points. However the two segments at the start/end of the frontier contour carry one corner point.\n\
\n\
# the single 3D point representing a surface frontier\n\
geometry_msgs/Point p\n\
# the length of the frontier in meters\n\
float32 length\n\
# the length of the parent frontier contour in meters\n\
float32 parent_length\n\
# the corner points associated with the frontier representative\n\
geometry_msgs/Point corner_1\n\
geometry_msgs/Point corner_2\n\
# the two corner points of the parent frontier contour containing the frontier\n\
geometry_msgs/Point parent_corner_1\n\
geometry_msgs/Point parent_corner_2\n\
# surface trend vector\n\
geometry_msgs/Point v\n\
# tangent to the surface frontier contour at representative point p\n\
geometry_msgs/Point f_grad\n\
# surface normal at p oriented towards the reachable portion of the environment\n\
geometry_msgs/Point n\n\
# Coeffcient of the quadratic used to approximate surface trend curve\n\
float64 a\n\
# if the representative is from the surface the robot traversed\n\
bool is_floor\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p);
      stream.next(m.length);
      stream.next(m.parent_length);
      stream.next(m.corner_1);
      stream.next(m.corner_2);
      stream.next(m.parent_corner_1);
      stream.next(m.parent_corner_2);
      stream.next(m.v);
      stream.next(m.f_grad);
      stream.next(m.n);
      stream.next(m.a);
      stream.next(m.is_floor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SurfaceFrontierRepresentative_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exploration3d_msgs::SurfaceFrontierRepresentative_<ContainerAllocator>& v)
  {
    s << indent << "p: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.p);
    s << indent << "length: ";
    Printer<float>::stream(s, indent + "  ", v.length);
    s << indent << "parent_length: ";
    Printer<float>::stream(s, indent + "  ", v.parent_length);
    s << indent << "corner_1: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.corner_1);
    s << indent << "corner_2: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.corner_2);
    s << indent << "parent_corner_1: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.parent_corner_1);
    s << indent << "parent_corner_2: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.parent_corner_2);
    s << indent << "v: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.v);
    s << indent << "f_grad: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.f_grad);
    s << indent << "n: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.n);
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "is_floor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_floor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORATION3D_MSGS_MESSAGE_SURFACEFRONTIERREPRESENTATIVE_H
