// Auto-generated. Do not edit!

// (in-package navigation_3d_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class PathNavigationFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.base_position = null;
      this.next_wp = null;
    }
    else {
      if (initObj.hasOwnProperty('base_position')) {
        this.base_position = initObj.base_position
      }
      else {
        this.base_position = new geometry_msgs.msg.PoseStamped();
      }
      if (initObj.hasOwnProperty('next_wp')) {
        this.next_wp = initObj.next_wp
      }
      else {
        this.next_wp = new geometry_msgs.msg.PoseStamped();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PathNavigationFeedback
    // Serialize message field [base_position]
    bufferOffset = geometry_msgs.msg.PoseStamped.serialize(obj.base_position, buffer, bufferOffset);
    // Serialize message field [next_wp]
    bufferOffset = geometry_msgs.msg.PoseStamped.serialize(obj.next_wp, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PathNavigationFeedback
    let len;
    let data = new PathNavigationFeedback(null);
    // Deserialize message field [base_position]
    data.base_position = geometry_msgs.msg.PoseStamped.deserialize(buffer, bufferOffset);
    // Deserialize message field [next_wp]
    data.next_wp = geometry_msgs.msg.PoseStamped.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += geometry_msgs.msg.PoseStamped.getMessageSize(object.base_position);
    length += geometry_msgs.msg.PoseStamped.getMessageSize(object.next_wp);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'navigation_3d_msgs/PathNavigationFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '70ad3497649caabc377bf9d2f09ab0e2';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    geometry_msgs/PoseStamped base_position
    geometry_msgs/PoseStamped next_wp
    
    
    ================================================================================
    MSG: geometry_msgs/PoseStamped
    # A Pose with reference coordinate frame and timestamp
    Header header
    Pose pose
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PathNavigationFeedback(null);
    if (msg.base_position !== undefined) {
      resolved.base_position = geometry_msgs.msg.PoseStamped.Resolve(msg.base_position)
    }
    else {
      resolved.base_position = new geometry_msgs.msg.PoseStamped()
    }

    if (msg.next_wp !== undefined) {
      resolved.next_wp = geometry_msgs.msg.PoseStamped.Resolve(msg.next_wp)
    }
    else {
      resolved.next_wp = new geometry_msgs.msg.PoseStamped()
    }

    return resolved;
    }
};

module.exports = PathNavigationFeedback;
