# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from exploration3d_msgs/GetFreeSpaceFrontierRepresentativesRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class GetFreeSpaceFrontierRepresentativesRequest(genpy.Message):
  _md5sum = "735bd3b58bedaeab43b3509fcd91d5f9"
  _type = "exploration3d_msgs/GetFreeSpaceFrontierRepresentativesRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/PoseStamped base_pose

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['base_pose']
  _slot_types = ['geometry_msgs/PoseStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       base_pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetFreeSpaceFrontierRepresentativesRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.base_pose is None:
        self.base_pose = geometry_msgs.msg.PoseStamped()
    else:
      self.base_pose = geometry_msgs.msg.PoseStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.base_pose.header.seq, _x.base_pose.header.stamp.secs, _x.base_pose.header.stamp.nsecs))
      _x = self.base_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.base_pose.pose.position.x, _x.base_pose.pose.position.y, _x.base_pose.pose.position.z, _x.base_pose.pose.orientation.x, _x.base_pose.pose.orientation.y, _x.base_pose.pose.orientation.z, _x.base_pose.pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.base_pose is None:
        self.base_pose = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.base_pose.header.seq, _x.base_pose.header.stamp.secs, _x.base_pose.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.base_pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.base_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.base_pose.pose.position.x, _x.base_pose.pose.position.y, _x.base_pose.pose.position.z, _x.base_pose.pose.orientation.x, _x.base_pose.pose.orientation.y, _x.base_pose.pose.orientation.z, _x.base_pose.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.base_pose.header.seq, _x.base_pose.header.stamp.secs, _x.base_pose.header.stamp.nsecs))
      _x = self.base_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.base_pose.pose.position.x, _x.base_pose.pose.position.y, _x.base_pose.pose.position.z, _x.base_pose.pose.orientation.x, _x.base_pose.pose.orientation.y, _x.base_pose.pose.orientation.z, _x.base_pose.pose.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.base_pose is None:
        self.base_pose = geometry_msgs.msg.PoseStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.base_pose.header.seq, _x.base_pose.header.stamp.secs, _x.base_pose.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.base_pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.base_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.base_pose.pose.position.x, _x.base_pose.pose.position.y, _x.base_pose.pose.position.z, _x.base_pose.pose.orientation.x, _x.base_pose.pose.orientation.y, _x.base_pose.pose.orientation.z, _x.base_pose.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from exploration3d_msgs/GetFreeSpaceFrontierRepresentativesResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import exploration3d_msgs.msg

class GetFreeSpaceFrontierRepresentativesResponse(genpy.Message):
  _md5sum = "5cc2c89628ede75606cb29c84583b52c"
  _type = "exploration3d_msgs/GetFreeSpaceFrontierRepresentativesResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """FreeSpaceFrontierRepresentative[] frontiers

================================================================================
MSG: exploration3d_msgs/FreeSpaceFrontierRepresentative
# A freespace frontier representative is the centroid of a group of connected freespace frontier voxels of some size 

# the centroid of the freespace frontier voxel cluster
geometry_msgs/Point p
# the normal to the freespace frontier voxel surface at centroid
geometry_msgs/Vector3 n
# number of voxels in the freespace frontier cluster
uint32 nvx

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['frontiers']
  _slot_types = ['exploration3d_msgs/FreeSpaceFrontierRepresentative[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       frontiers

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetFreeSpaceFrontierRepresentativesResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.frontiers is None:
        self.frontiers = []
    else:
      self.frontiers = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.frontiers)
      buff.write(_struct_I.pack(length))
      for val1 in self.frontiers:
        _v1 = val1.p
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v2 = val1.n
        _x = _v2
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_get_struct_I().pack(val1.nvx))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.frontiers is None:
        self.frontiers = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.frontiers = []
      for i in range(0, length):
        val1 = exploration3d_msgs.msg.FreeSpaceFrontierRepresentative()
        _v3 = val1.p
        _x = _v3
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v4 = val1.n
        _x = _v4
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (val1.nvx,) = _get_struct_I().unpack(str[start:end])
        self.frontiers.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.frontiers)
      buff.write(_struct_I.pack(length))
      for val1 in self.frontiers:
        _v5 = val1.p
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v6 = val1.n
        _x = _v6
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_get_struct_I().pack(val1.nvx))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.frontiers is None:
        self.frontiers = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.frontiers = []
      for i in range(0, length):
        val1 = exploration3d_msgs.msg.FreeSpaceFrontierRepresentative()
        _v7 = val1.p
        _x = _v7
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v8 = val1.n
        _x = _v8
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (val1.nvx,) = _get_struct_I().unpack(str[start:end])
        self.frontiers.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
class GetFreeSpaceFrontierRepresentatives(object):
  _type          = 'exploration3d_msgs/GetFreeSpaceFrontierRepresentatives'
  _md5sum = '42bad0289ab9e4d55cd64632c44f3f09'
  _request_class  = GetFreeSpaceFrontierRepresentativesRequest
  _response_class = GetFreeSpaceFrontierRepresentativesResponse
